services:
  db:
    image: postgres:15-alpine
    container_name: todo_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todoapp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: todo_app
    restart: always
    ports:
      - "8000:8000"
      - "8080:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/todoapp
    depends_on:
      - db

volumes:
  postgres_data:
